services:
  firebase:
    build: .
    volumes:
      - ./data:/app/data
    ports:
      - "4000:4000" # UI
      - "8080:8080" # Firestore
      - "9099:9099" # Auth
      - "9199:9199" # Storage
      - "4400:4400" # Hub
      - "4500:4500" # Logging
    stop_grace_period: 60s
    # We use a tty to allow for better signaling on exit
    tty: true
    # We want to make sure it gracefully handles SIGTERM for export-on-exit
    stop_signal: SIGINT

volumes:
  firebase_data:
